name: Publish a release to crates.io

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  upload-crate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Setup toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Publish sqlet-core
      uses: actions-rs/cargo@v1
      env:
        CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}
      with:
        command: publish
        args: --all-features sqlet-core
        args: --token $CARGO_TOKEN

    - name: Publish sqlet-macros
      uses: actions-rs/cargo@v1
      env:
        CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}
      with:
        command: publish
        args: --all-features sqlet-macros
        args: --token $CARGO_TOKEN

    - name: Publish sqlet
      uses: actions-rs/cargo@v1
      env:
        CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}
      with:
        command: publish
        args: --all-features sqlet
        args: --token $CARGO_TOKEN

    - name: Publish sqlet-cli
      uses: actions-rs/cargo@v1
      env:
        CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}
      with:
        command: publish
        args: --all-features sqlet-cli
        args: --token $CARGO_TOKEN
